from itertools import combinations

countries = ["USA",
             "Afghanistan",
             "Afr.Other NS",
             "Africa N.NES",
             "Albania",
             "Algeria",
             "Angola",
             "Areas NES",
             "Argentina",
             "Armenia",
             "Asia NES",
             "Asia West NS",
             "Australia",
             "Austria",
             "Azerbaijan",
             "Bahamas",
             "Bahrain",
             "Bangladesh",
             "Barbados",
             "Belarus",
             "Belgium-Lux",
             "Belize",
             "Benin",
             "Bermuda",
             "Bolivia",
             "Bosnia Herzg",
             "Br.Antr.Terr",
             "Brazil",
             "Bulgaria",
             "Burkina Faso",
             "Burundi",
             "CACM NES",
             "Cambodia",
             "Cameroon",
             "Canada",
             "Carib. NES",
             "Cent.Afr.Rep",
             "Chad",
             "Chile",
             "China",
             "China HK SAR",
             "China MC SAR",
             "China SC",
             "Colombia",
             "Congo",
             "Costa Rica",
             "Cote Divoire",
             "Croatia",
             "Cuba",
             "Cyprus",
             "Czech Rep",
             "Czechoslovak",
             "Dem.Rp.Congo",
             "Denmark",
             "Djibouti",
             "Dominican Rp",
             "E Europe NES",
             "EEC NES",
             "Ecuador",
             "Egypt",
             "El Salvador",
             "Eq.Guinea",
             "Estonia",
             "Ethiopia",
             "Eur. EFTA NS",
             "Eur.Other NE",
             "Falkland Is",
             "Fiji",
             "Finland",
             "Fm German DR",
             "Fm German FR",
             "Fm USSR",
             "Fm Yemen AR",
             "Fm Yemen Ar",
             "Fm Yemen Dm",
             "Fm Yugoslav",
             "Fr Ind O",
             "Fr.Guiana",
             "France,Monac",
             "Gabon",
             "Gambia",
             "Georgia",
             "Germany",
             "Ghana",
             "Gibraltar",
             "Greece",
             "Greenland",
             "Guadeloupe",
             "Guatemala",
             "Guinea",
             "GuineaBissau",
             "Guyana",
             "Haiti",
             "Honduras",
             "Hungary",
             "Iceland",
             "India",
             "Indonesia",
             "Int Org",
             "Iran",
             "Iraq",
             "Ireland",
             "Israel",
             "Italy",
             "Jamaica",
             "Japan",
             "Jordan",
             "Kazakhstan",
             "Kenya",
             "Kiribati",
             "Korea D P Rp",
             "Korea Rep.",
             "Kuwait",
             "Kyrgyzstan",
             "LAIA NES",
             "Lao P.Dem.R",
             "Latvia",
             "Lebanon",
             "Liberia",
             "Libya",
             "Lithuania",
             "Madagascar",
             "Malawi",
             "Malaysia",
             "Mali",
             "Malta",
             "Mauritania",
             "Mauritius",
             "Mexico",
             "Mongolia",
             "Morocco",
             "Mozambique",
             "Myanmar",
             "Nepal",
             "Neth.Ant.Aru",
             "Netherlands",
             "Neutral Zone",
             "New Calednia",
             "New Zealand",
             "Nicaragua",
             "Niger",
             "Nigeria",
             "Norway",
             "Occ.Pal.Terr",
             "Oman",
             "Oth.Oceania",
             "Pakistan",
             "Panama",
             "Papua N.Guin",
             "Paraguay",
             "Peru",
             "Philippines",
             "Poland",
             "Portugal",
             "Qatar",
             "Rep Moldova",
             "Romania",
             "Russian Fed",
             "Rwanda",
             "Samoa",
             "Saudi Arabia",
             "Senegal",
             "Seychelles",
             "Sierra Leone",
             "Singapore",
             "Slovakia",
             "Slovenia",
             "Somalia",
             "South Africa",
             "Spain",
             "Sri Lanka",
             "St.Helena",
             "St.Kt-Nev-An",
             "St.Pierre Mq",
             "Sudan",
             "Suriname",
             "Sweden",
             "Switz.Liecht",
             "Syria",
             "TFYR Macedna",
             "Taiwan",
             "Tajikistan",
             "Tanzania",
             "Thailand",
             "Togo",
             "Trinidad Tbg",
             "Tunisia",
             "Turkey",
             "Turkmenistan",
             "UK",
             "US NES",
             "Uganda",
             "Ukraine",
             "Untd Arab Em",
             "Uruguay",
             "Uzbekistan",
             "Venezuela",
             "Viet Nam",
             "Yemen",
             "Yugoslavia",
             "Zambia",
             "Zimbabwe",
             "World",
             "China FTZ"]

a_subset_of_countries = ["USA",
                         "Afghanistan",
                         "Argentina",
                         "Australia",
                         "Bahrain",
                         "Bangladesh",
                         "Barbados",
                         "Belgium-Lux",
                         "Brazil",
                         "Canada",
                         "Chile",
                         "China",
                         "Denmark",
                         "Egypt",
                         "France,Monac",
                         "Germany",
                         "Greece",
                         "Greenland",
                         "Hungary",
                         "Iceland",
                         "India",
                         "Indonesia",
                         "Iran",
                         "Iraq",
                         "Ireland",
                         "Israel",
                         "Italy",
                         "Japan",
                         "Kuwait",
                         "Malaysia",
                         "Mexico",
                         "Netherlands",
                         "New Zealand",
                         "Pakistan",
                         "Poland",
                         "Portugal",
                         "Qatar",
                         "Romania",
                         "Russian Fed",
                         "Saudi Arabia",
                         "Singapore",
                         "South Africa",
                         "Spain",
                         "Sweden",
                         "Turkey",
                         "UK",
                         "Untd Arab Em",
                         "Uruguay",
                         "Viet Nam",
                         "China FTZ"]

country_to_index_map = {}
index_to_country_map = {}

index = 0
for c in countries:
    country_to_index_map[c] = index
    index_to_country_map[index] = c
    index += 1


def is_valid_country(c): return c in country_to_index_map


def index_of_country(c): return countries.index(c)


world_excluded_list = None


def world_excluded_countries_list():
    global world_excluded_list
    if world_excluded_list is None:
        world_excluded_list = list(countries)
        world_excluded_list.remove("World")
    return world_excluded_list


def country_pairs(only_these_countries=world_excluded_countries_list()): return combinations(only_these_countries, 2)


falklands_war_countries = ["USA", "UK", "Argentina", "France,Monac", "Libya", "Fm USSR", "Israel", "Peru", "Brazil"]
falkland_related_war_countries = ['Argentina','Brazil','Fm USSR','Peru','Libya','Israel','UK','USA','Denmark','Portugal','Norway','Sweden']


